# Generated by Django 4.2.4 on 2023-09-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_businesspartner"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="business_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.businesspartner",
            ),
        ),
        migrations.AddField(
            model_name="hotelbooking",
            name="business_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.businesspartner",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="business_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resources.businesspartner",
            ),
        ),
    ]
